# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d508e3853647b43985fd74c36c0d12b59182b710dbe7d636e1ac2c2cdd55c7a1dfbf8bbe070a2cf30713539b8fc7ddeb9e76f99872cd7b671f7f4f447884727

test:
  secret_key_base: d3f45b5ccea455b10c37ad909205750f84fd2eb62ce404962d89872baa03b63d23da9dbbc035dcb02a8db5a592165f1e8e83f639a9714d9d1c090f8cba5d447a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
